let strip = neopixel.create(DigitalPin.P13, 64, NeoPixelMode.RGB)
let range = strip.range(0, 15)
let range2 = strip.range(16, 31)
let range3 = strip.range(32, 47)
let range4 = strip.range(48, 63)
range.setBrightness(20)
range2.setBrightness(20)
range3.setBrightness(20)
range4.setBrightness(20)
strip.setMatrixWidth(8)
strip.setPixelColor(0, neopixel.colors(NeoPixelColors.Yellow))
strip.show()
basic.forever(function () {
    serial.writeNumber(input.lightLevel())
    serial.writeLine("")
    if (input.lightLevel() > 220) {
        strip.rotate(1)
        basic.pause(100)
        strip.show()
    } else if (input.lightLevel() > 210) {
        strip.showRainbow(1, 360)
        strip.show()
        basic.pause(100)
        strip.setPixelColor(0, neopixel.colors(NeoPixelColors.Black))
    } else {
        strip.showColor(neopixel.colors(NeoPixelColors.Black))
        range.showBarGraph(input.soundLevel(), 100)
        range2.showBarGraph(input.soundLevel(), 100)
        range3.showBarGraph(input.soundLevel(), 100)
        range4.showBarGraph(input.soundLevel(), 100)
        strip.show()
    }
})
